import { getDb } from "../../db/database.js";
export interface CompetitorMetricRow { name:string; isClient:boolean; rating:number|null; reviewCount:number|null; claimed:boolean|null; websiteSpeedMs:number|null; schemaDetected:boolean|null; localPackPresence:string; organicScore:number|null; evidenceLevel:"profile"|"audit"|"not_checked"; }
export interface CompetitorBenchmarkReport { targetBusiness:string;niche:string;city:string;summary:string;metrics:CompetitorMetricRow[];keyDifferences:string[];winningStrategy:string;generatedAt:string;dataSource:"database"|"not_checked"; }
export function generateCompetitorBenchmark(params:{leadId?:string;businessName:string;niche:string;city:string;rating?:number|null;reviewCount?:number|null;claimed?:number|boolean;websiteScore?:number|null;}):CompetitorBenchmarkReport {
 const db=getDb();let found:any[]=[];try{found=db.prepare(`SELECT l.business_name,l.gmb_rating,l.gmb_review_count,l.gmb_claimed,(SELECT a.score FROM audits a WHERE a.lead_id=l.id AND a.audit_type='website' AND a.status='completed' ORDER BY datetime(a.created_at) DESC LIMIT 1) website_score FROM leads l WHERE (l.id!=? OR ?='') AND LOWER(COALESCE(l.niche,''))=LOWER(?) AND LOWER(COALESCE(l.city,''))=LOWER(?) LIMIT 5`).all(params.leadId||"",params.leadId||"",params.niche||"",params.city||"") as any[];}catch{}
 const target:CompetitorMetricRow={name:params.businessName,isClient:true,rating:params.rating??null,reviewCount:params.reviewCount??null,claimed:params.claimed==null?null:Boolean(params.claimed),websiteSpeedMs:null,schemaDetected:null,localPackPresence:"Not checked",organicScore:params.websiteScore??null,evidenceLevel:params.websiteScore!=null?"audit":"profile"};
 const competitors=found.map((c):CompetitorMetricRow=>({name:c.business_name,isClient:false,rating:c.gmb_rating??null,reviewCount:c.gmb_review_count??null,claimed:c.gmb_claimed==null?null:Boolean(c.gmb_claimed),websiteSpeedMs:null,schemaDetected:null,localPackPresence:"Not checked",organicScore:c.website_score??null,evidenceLevel:c.website_score!=null?"audit":"profile"}));
 const reviewLeaders=competitors.filter(c=>c.reviewCount!=null&&params.reviewCount!=null).sort((a,b)=>(b.reviewCount||0)-(a.reviewCount||0));const differences:string[]=[];if(reviewLeaders[0]){const gap=(reviewLeaders[0].reviewCount||0)-(params.reviewCount||0);differences.push(gap>0?`${reviewLeaders[0].name} has ${gap} more recorded reviews.`:`${params.businessName} has comparable or higher recorded review volume.`);}if(params.websiteScore==null)differences.push("The target website has no completed website audit score in this comparison.");
 return {targetBusiness:params.businessName,niche:params.niche||"Local Service",city:params.city||"Local Area",summary:competitors.length?`Compared ${params.businessName} with ${competitors.length} stored businesses matching the same niche and city. Map positions, speed, and schema remain unverified unless a live audit supplies them.`:"No same-niche, same-city competitors with stored evidence were found. No benchmark leaders were invented.",metrics:[target,...competitors],keyDifferences:differences,winningStrategy:"Run live website audits and import attributable local-search results before recommending a ranking-gap strategy.",generatedAt:new Date().toISOString(),dataSource:competitors.length?"database":"not_checked"};
}