import { getDb } from "../../db/database.js";
import { v4 as uuidv4 } from "uuid";
import { runWebsiteAudit } from "./website.js";
export interface RecurringAuditJobResult { businessId:string;clientId:string;businessName:string;previousScore:number|null;newScore:number|null;scoreDelta:number|null;auditId:string;status:"success"|"skipped"|"failed";timestamp:string;message?:string; }
export interface RecurringScheduleStatus { totalRetainedBusinesses:number;activeAutomatedAudits:number;lastRunTimestamp:string|null;nextScheduledRun:string;recentRunHistory:RecurringAuditJobResult[]; }
let lastRecurringRunTime:string|null=null;const recentAuditHistory:RecurringAuditJobResult[]=[];
export async function executeRecurringClientAudits():Promise<RecurringAuditJobResult[]> {
 const db=getDb(),now=new Date().toISOString(),next=new Date(Date.now()+30*86400000).toISOString(),results:RecurringAuditJobResult[]=[];
 const businesses=db.prepare(`SELECT b.*,c.lifecycle_stage FROM client_businesses b JOIN seo_clients c ON b.client_id=c.id WHERE c.lifecycle_stage IN ('active','onboarding')`).all() as any[];
 for(const biz of businesses){const runId=uuidv4(),previous=biz.last_website_audit_score==null?null:Number(biz.last_website_audit_score);if(!biz.website){const item:RecurringAuditJobResult={businessId:biz.id,clientId:biz.client_id,businessName:biz.name,previousScore:previous,newScore:null,scoreDelta:null,auditId:"",status:"skipped",timestamp:now,message:"No website URL is configured; no score was generated."};db.prepare("INSERT INTO recurring_audit_runs(id,business_id,status,previous_score,error_message) VALUES(?,?, 'skipped',?,?)").run(runId,biz.id,previous,item.message||"Skipped");results.push(item);recentAuditHistory.unshift(item);continue;}
  try{const audit=await runWebsiteAudit({website:biz.website,businessName:biz.name,city:biz.city,state:biz.state});const auditId=uuidv4();db.prepare(`INSERT INTO audits(id,lead_id,client_id,business_id,audit_type,score,verdict,data_json,target_name,status,created_at,updated_at) VALUES(?,?,?,?, 'website',?,?,?,?, 'completed',?,?)`).run(auditId,biz.lead_id||null,biz.client_id,biz.id,audit.score,audit.verdict,JSON.stringify({...audit,recurringCycle:"monthly",evidenceSource:"live_website_fetch"}),biz.name,now,now);db.prepare("UPDATE client_businesses SET last_website_audit_score=?,next_audit_at=?,updated_at=? WHERE id=?").run(audit.score,next,now,biz.id);db.prepare("INSERT INTO recurring_audit_runs(id,business_id,status,previous_score,new_score,audit_id) VALUES(?,?, 'success',?,?,?)").run(runId,biz.id,previous,audit.score,auditId);const item:RecurringAuditJobResult={businessId:biz.id,clientId:biz.client_id,businessName:biz.name,previousScore:previous,newScore:audit.score,scoreDelta:previous==null?null:audit.score-previous,auditId,status:"success",timestamp:now};results.push(item);recentAuditHistory.unshift(item);}catch(error:any){const message=String(error?.message||"Audit failed").slice(0,500);db.prepare("INSERT INTO recurring_audit_runs(id,business_id,status,previous_score,error_message) VALUES(?,?, 'failed',?,?)").run(runId,biz.id,previous,message);const item:RecurringAuditJobResult={businessId:biz.id,clientId:biz.client_id,businessName:biz.name||"Unknown",previousScore:previous,newScore:null,scoreDelta:null,auditId:"",status:"failed",timestamp:now,message};results.push(item);recentAuditHistory.unshift(item);}}
 lastRecurringRunTime=now;if(recentAuditHistory.length>50)recentAuditHistory.length=50;return results;
}
export function getRecurringAuditStatus():RecurringScheduleStatus {const db=getDb();let total=0;try{total=Number((db.prepare(`SELECT COUNT(*) cnt FROM client_businesses b JOIN seo_clients c ON b.client_id=c.id WHERE c.lifecycle_stage IN ('active','onboarding')`).get() as any)?.cnt||0);}catch{}const next=new Date(Date.now()+30*86400000);return {totalRetainedBusinesses:total,activeAutomatedAudits:total,lastRunTimestamp:lastRecurringRunTime,nextScheduledRun:next.toISOString(),recentRunHistory:recentAuditHistory.slice(0,15)};}