export interface ReviewSentimentTheme { topic:string; sentiment:"positive"|"negative"|"neutral"; mentionsCount:number; sampleQuote:string; }
export interface ReviewSentimentReport { businessName:string; totalReviewsAnalyzed:number; averageRating:number|null; sentimentScore:number|null; positivePercentage:number; neutralPercentage:number; negativePercentage:number; topPraiseThemes:ReviewSentimentTheme[]; criticalConcerns:ReviewSentimentTheme[]; executiveTakeaway:string; recommendedReviewStrategy:string; generatedAt:string; dataSource:"review_text"|"not_checked"; }
export function generateReviewSentimentAnalysis(params:{businessName:string;niche?:string;rating?:number|null;reviewCount?:number|null;reviews?:string[];}):ReviewSentimentReport {
  const reviews=(params.reviews||[]).map(v=>v.trim()).filter(Boolean);
  if(!reviews.length)return {businessName:params.businessName,totalReviewsAnalyzed:0,averageRating:params.rating??null,sentimentScore:null,positivePercentage:0,neutralPercentage:0,negativePercentage:0,topPraiseThemes:[],criticalConcerns:[],executiveTakeaway:"No review text was supplied, so sentiment and themes were not calculated.",recommendedReviewStrategy:"Import recent review text with source URLs and dates before presenting sentiment findings. Use the known rating and review count only as profile metrics.",generatedAt:new Date().toISOString(),dataSource:"not_checked"};
  const positive=/\b(great|excellent|professional|fast|helpful|recommend|friendly|quality|clean|on time)\b/i,negative=/\b(bad|poor|late|rude|expensive|delay|never|worst|problem|unresponsive)\b/i;
  let pos=0,neg=0;for(const text of reviews){if(positive.test(text))pos++;else if(negative.test(text))neg++;}const neutral=reviews.length-pos-neg;
  const pct=(n:number)=>Math.round(n/reviews.length*100);
  return {businessName:params.businessName,totalReviewsAnalyzed:reviews.length,averageRating:params.rating??null,sentimentScore:pct(pos),positivePercentage:pct(pos),neutralPercentage:pct(neutral),negativePercentage:pct(neg),topPraiseThemes:[],criticalConcerns:[],executiveTakeaway:`Sentiment was calculated from ${reviews.length} supplied review texts. Theme extraction requires a larger attributed sample.`,recommendedReviewStrategy:"Reply to unresolved reviews and request feedback after completed jobs without offering incentives.",generatedAt:new Date().toISOString(),dataSource:"review_text"};
}