import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { EmailComposer } from "../components/EmailComposer";
import { useToast } from "../components/Toast";
import { Button } from "../components/ui/Button";
import { Card, CardBody, CardHeader } from "../components/ui/Card";
import { PageHeader } from "../components/ui/PageHeader";
import { IconCheckCircle, IconMail, IconShield } from "../components/ui/Icons";
import {
  createOutreachTemplate, createSmtpAccount, deleteSmtpAccount, fetchAppSettings, fetchOutreachTemplates,
  fetchSmtpAccounts, sendSmtpAccountTest, updateAppSettings,
  type AppProfileSettings, type CampaignTemplate, type SmtpAccount,
} from "../lib/api";
import { dispatchSettingsUpdated, getAgencyInitials } from "../lib/branding";
import { smtpProviderPresets } from "../lib/emailSender";
import { formatTimeZoneLabel, getTimeZoneGroups } from "../lib/timezones";

const sources = [
  { value: "general", label: "All prospects" }, { value: "yellowpages", label: "Yellow Pages" },
  { value: "gmb_scraper", label: "Google Maps" }, { value: "state_directory", label: "State Directory" },
  { value: "yelp_scraper", label: "Yelp" }, { value: "bbb_scraper", label: "BBB" },
];
const blankProfile: AppProfileSettings = { agencyName: "", agencyEmail: "", agencyPhone: "", businessAddress: "", defaultCity: "", defaultState: "", agencyLogoUrl: "", timezone: "America/New_York", brandNotes: "", agencyWebsite: "", bookingUrl: "", country: "", postalCode: "", taxId: "", defaultCurrency: "USD", invoicePrefix: "INV", paymentTermsDays: 15, invoiceFooter: "", googleClientId: "", googleClientSecret: "", googlePlacesApiKey: "", dataForSeoLogin: "", dataForSeoPassword: "", updatedAt: "" };
type SettingsTab = "general" | "outreach";
const inputClass = "mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-[13px] text-slate-900 shadow-sm placeholder:text-slate-400";
const labelClass = "block text-xs font-semibold text-slate-700";

function tabFromHash(hash: string): SettingsTab { return hash.includes("outreach") ? "outreach" : "general"; }
function Field({ label, value, onChange, placeholder = "", type = "text" }: { label: string; value: string | number; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label className={labelClass}>{label}<input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className={inputClass} /></label>; }

export function SettingsPage() {
  const location = useLocation(); const navigate = useNavigate(); const { showToast } = useToast();
  const [tab, setTab] = useState<SettingsTab>(() => tabFromHash(location.hash));
  const [profile, setProfile] = useState<AppProfileSettings>(blankProfile);
  const [smtpAccounts, setSmtpAccounts] = useState<SmtpAccount[]>([]);
  const [selectedSmtpId, setSelectedSmtpId] = useState("");
  const [smtpName, setSmtpName] = useState("Primary sender"); const [smtpHost, setSmtpHost] = useState("");
  const [smtpPort, setSmtpPort] = useState(587); const [smtpSecure, setSmtpSecure] = useState(false);
  const [smtpUsername, setSmtpUsername] = useState(""); const [smtpPassword, setSmtpPassword] = useState("");
  const [smtpFromName, setSmtpFromName] = useState(""); const [smtpFromEmail, setSmtpFromEmail] = useState(""); const [smtpTestEmail, setSmtpTestEmail] = useState("");
  const [templateSource, setTemplateSource] = useState("general"); const [templateName, setTemplateName] = useState("General prospecting");
  const [templateSubject, setTemplateSubject] = useState("Quick idea for {{business_name}}"); const [templateBody, setTemplateBody] = useState("Hi {{business_name}},\n\nI noticed a few local SEO opportunities in {{city}} that may be limiting enquiries.\n\nWould you like me to send the short audit summary?\n\nBest,\n{{sender_name}}");
  const [templateBodyHtml, setTemplateBodyHtml] = useState(""); const [sendIntervalMs, setSendIntervalMs] = useState(1000);
  const [followUpEnabled, setFollowUpEnabled] = useState(true); const [followUpDelayHours, setFollowUpDelayHours] = useState(72);
  const [followUpSubject, setFollowUpSubject] = useState("Re: {{business_name}} audit findings"); const [followUpBody, setFollowUpBody] = useState("Hi {{business_name}},\n\nJust following up in case the audit note was missed. I can still send the priority findings for {{city}}.\n\nBest,\n{{sender_name}}");
  const [followUpBodyHtml, setFollowUpBodyHtml] = useState(""); const [maxRetries, setMaxRetries] = useState(1);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");

  const timeZones = useMemo(() => getTimeZoneGroups(profile.timezone), [profile.timezone]);
  useEffect(() => setTab(tabFromHash(location.hash)), [location.hash]);
  useEffect(() => { void (async () => { setLoading(true); try { const [settings, smtp, templates] = await Promise.all([fetchAppSettings(), fetchSmtpAccounts(), fetchOutreachTemplates({ source: "general" })]); setProfile({ ...blankProfile, ...settings.profile }); setSmtpAccounts(smtp.items); setSelectedSmtpId(smtp.items[0]?.id || ""); applyTemplate(templates.recommended, "general"); } catch (err) { setError(err instanceof Error ? err.message : "Settings could not be loaded."); } finally { setLoading(false); } })(); }, []);

  function switchTab(next: SettingsTab) { setTab(next); navigate(next === "outreach" ? "/settings/profile#outreach" : "/settings/profile", { replace: true }); }
  function setProfileField<K extends keyof AppProfileSettings>(key: K, value: AppProfileSettings[K]) { setProfile((current) => ({ ...current, [key]: value })); }
  function applyTemplate(template: CampaignTemplate, source = templateSource) { setTemplateSource(source); setTemplateName(template.name); setTemplateSubject(template.subject); setTemplateBody(template.body); setTemplateBodyHtml(template.body_html || ""); setSendIntervalMs(template.send_interval_ms); setFollowUpEnabled(template.follow_up_enabled); setFollowUpDelayHours(template.follow_up_delay_hours); setFollowUpSubject(template.follow_up_subject); setFollowUpBody(template.follow_up_body); setFollowUpBodyHtml(template.follow_up_body_html || ""); setMaxRetries(template.max_retries); }
  async function loadTemplate(source: string) { try { const data = await fetchOutreachTemplates({ source }); applyTemplate(data.recommended, source); } catch (err) { setError(err instanceof Error ? err.message : "Template could not be loaded."); } }
  async function loadSenders() { const data = await fetchSmtpAccounts(); setSmtpAccounts(data.items); setSelectedSmtpId((current) => current || data.items[0]?.id || ""); }

  async function handleLogoUpload(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; event.target.value = ""; if (!file) return;
    if (!file.type.startsWith("image/") || file.size > 2 * 1024 * 1024) { setError("Choose an image up to 2 MB."); return; }
    const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || "")); reader.onerror = () => reject(new Error("Logo could not be read.")); reader.readAsDataURL(file); });
    setProfileField("agencyLogoUrl", dataUrl); setMessage("Logo is ready. Save the profile to apply it.");
  }
  async function saveProfile() { setSaving(true); setError(""); try { const updated = await updateAppSettings(profile); setProfile({ ...blankProfile, ...updated }); dispatchSettingsUpdated(updated); showToast("success", "Agency profile saved"); } catch (err) { setError(err instanceof Error ? err.message : "Profile could not be saved."); } finally { setSaving(false); } }
  function applyPreset(id: string) { const preset = smtpProviderPresets.find((item) => item.id === id); if (!preset) return; setSmtpHost(preset.host); setSmtpPort(preset.port); setSmtpSecure(preset.secure); if (!smtpName || smtpName === "Primary sender") setSmtpName(`${preset.label} sender`); }
  async function saveSender() { if (!smtpHost || !smtpUsername || !smtpPassword) { setError("SMTP host, username, and password are required."); return; } setBusy(true); setError(""); try { await createSmtpAccount({ name: smtpName, host: smtpHost, port: smtpPort, secure: smtpSecure, username: smtpUsername, password: smtpPassword, from_name: smtpFromName || undefined, from_email: smtpFromEmail || undefined, is_active: true }); setSmtpPassword(""); await loadSenders(); showToast("success", "Sender account saved"); } catch (err) { setError(err instanceof Error ? err.message : "Sender could not be saved."); } finally { setBusy(false); } }
  async function testSender() { if (!selectedSmtpId || !smtpTestEmail) { setError("Select a sender and enter a test recipient."); return; } setBusy(true); setError(""); try { await sendSmtpAccountTest(selectedSmtpId, smtpTestEmail); showToast("success", "Test email sent"); } catch (err) { setError(err instanceof Error ? err.message : "Test email could not be sent."); } finally { setBusy(false); } }
  async function removeSender(id: string) { setBusy(true); try { await deleteSmtpAccount(id); await loadSenders(); showToast("success", "Sender removed"); } catch (err) { setError(err instanceof Error ? err.message : "Sender could not be removed."); } finally { setBusy(false); } }
  async function saveTemplate() { if (!templateSubject.trim() || !templateBody.trim()) { setError("Subject and email body are required."); return; } setBusy(true); setError(""); try { const saved = await createOutreachTemplate({ name: templateName, sourceKey: templateSource, subject: templateSubject, body: templateBody, bodyHtml: templateBodyHtml, sendIntervalMs, followUpEnabled, followUpDelayHours, followUpSubject, followUpBody, followUpBodyHtml, maxRetries, isDefault: true }); applyTemplate(saved, templateSource); showToast("success", "Outreach defaults saved"); } catch (err) { setError(err instanceof Error ? err.message : "Outreach defaults could not be saved."); } finally { setBusy(false); } }

  if (loading) return <section className="space-y-5"><div className="h-20 animate-pulse rounded-2xl bg-white"/><div className="h-96 animate-pulse rounded-2xl bg-white"/></section>;
  return <section className="page-enter space-y-6">
    <PageHeader title="Settings" description="Configure your agency identity and the defaults your team uses every day." actions={<Link to="/settings/api" className="inline-flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 text-xs font-semibold text-slate-700 shadow-sm hover:border-indigo-300"><IconShield size={15}/>API setup</Link>} />
    <div className="flex gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-sm sm:w-fit">{([{ key: "general", label: "Agency profile" }, { key: "outreach", label: "Outreach defaults" }] as const).map((item) => <button key={item.key} type="button" onClick={() => switchTab(item.key)} className={`rounded-lg px-4 py-2 text-xs font-semibold transition ${tab === item.key ? "bg-slate-900 text-white shadow" : "text-slate-500 hover:bg-slate-50 hover:text-slate-900"}`}>{item.label}</button>)}</div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs text-rose-700">{error}<button type="button" onClick={() => setError("")} className="float-right font-bold">×</button></div>}
    {message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-700">{message}</div>}

    {tab === "general" && <div className="space-y-5">
      <Card><CardHeader title="Agency identity" subtitle="Used in reports, pitch pages, client portals, and future invoices."/><CardBody><div className="grid gap-6 lg:grid-cols-[220px_1fr]">
        <div><div className="flex h-32 items-center justify-center rounded-2xl border border-dashed border-slate-200 bg-slate-50">{profile.agencyLogoUrl ? <img src={profile.agencyLogoUrl} alt="Agency logo" className="max-h-24 max-w-[180px] object-contain"/> : <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-600 text-lg font-bold text-white">{getAgencyInitials(profile.agencyName)}</div>}</div><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(event) => void handleLogoUpload(event)} className="mt-3 block w-full text-[11px] text-slate-500 file:mr-2 file:rounded-lg file:border-0 file:bg-slate-900 file:px-3 file:py-2 file:text-xs file:font-semibold file:text-white"/>{profile.agencyLogoUrl && <button type="button" onClick={() => setProfileField("agencyLogoUrl", "")} className="mt-2 text-[11px] font-semibold text-rose-600">Remove logo</button>}</div>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Agency name" value={profile.agencyName} onChange={(v) => setProfileField("agencyName", v)} placeholder="Northstar Local"/><Field label="Website" value={profile.agencyWebsite || ""} onChange={(v) => setProfileField("agencyWebsite", v)} placeholder="https://agency.com"/><Field label="Booking link" type="url" value={profile.bookingUrl || ""} onChange={(v) => setProfileField("bookingUrl", v)} placeholder="https://cal.com/your-agency"/><Field label="Contact email" type="email" value={profile.agencyEmail} onChange={(v) => setProfileField("agencyEmail", v)} placeholder="hello@agency.com"/><Field label="Phone" value={profile.agencyPhone} onChange={(v) => setProfileField("agencyPhone", v)} placeholder="+1 555 000 0000"/><label className={`${labelClass} sm:col-span-2`}>Brand and proposal context<textarea rows={4} value={profile.brandNotes} onChange={(e) => setProfileField("brandNotes", e.target.value)} placeholder="Your positioning, preferred tone, services, and differentiators." className={`${inputClass} h-auto py-2.5`}/></label></div>
      </div></CardBody></Card>

      <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader title="Business address" subtitle="Default legal and location details for documents."/><CardBody className="grid gap-4 sm:grid-cols-2"><label className={`${labelClass} sm:col-span-2`}>Street address<textarea rows={2} value={profile.businessAddress} onChange={(e) => setProfileField("businessAddress", e.target.value)} className={`${inputClass} h-auto py-2`}/></label><Field label="City" value={profile.defaultCity} onChange={(v) => setProfileField("defaultCity", v)}/><Field label="State / region" value={profile.defaultState} onChange={(v) => setProfileField("defaultState", v)}/><Field label="Postal code" value={profile.postalCode || ""} onChange={(v) => setProfileField("postalCode", v)}/><Field label="Country" value={profile.country || ""} onChange={(v) => setProfileField("country", v)}/><label className={`${labelClass} sm:col-span-2`}>Timezone<select value={profile.timezone} onChange={(e) => setProfileField("timezone", e.target.value)} className={inputClass}>{timeZones.map((group) => <optgroup key={group.label} label={group.label}>{group.options.map((zone) => <option key={zone} value={zone}>{formatTimeZoneLabel(zone)}</option>)}</optgroup>)}</select></label></CardBody></Card>
      <Card><CardHeader title="Invoice defaults" subtitle="Stored once so billing documents can be generated consistently."/><CardBody className="grid gap-4 sm:grid-cols-2"><Field label="Tax / registration ID" value={profile.taxId || ""} onChange={(v) => setProfileField("taxId", v)} placeholder="Optional"/><Field label="Default currency" value={profile.defaultCurrency || "USD"} onChange={(v) => setProfileField("defaultCurrency", v.toUpperCase())} placeholder="USD"/><Field label="Invoice prefix" value={profile.invoicePrefix || "INV"} onChange={(v) => setProfileField("invoicePrefix", v.toUpperCase())}/><Field label="Payment terms (days)" type="number" value={profile.paymentTermsDays ?? 15} onChange={(v) => setProfileField("paymentTermsDays", Math.max(0, Number(v) || 0))}/><label className={`${labelClass} sm:col-span-2`}>Invoice footer<textarea rows={3} value={profile.invoiceFooter || ""} onChange={(e) => setProfileField("invoiceFooter", e.target.value)} placeholder="Payment instructions or thank-you note." className={`${inputClass} h-auto py-2`}/></label></CardBody></Card></div>
      <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3"><p className="text-[11px] text-slate-500">{profile.updatedAt ? `Last saved ${new Date(profile.updatedAt).toLocaleString()}` : "Profile has not been saved yet."}</p><Button onClick={() => void saveProfile()} loading={saving}>Save agency profile</Button></div>
    </div>}

    {tab === "outreach" && <div className="space-y-5">
      <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3"><IconShield size={18} className="mt-0.5 shrink-0 text-amber-700"/><div><p className="text-xs font-semibold text-amber-900">Sending is currently paused</p><p className="mt-1 text-[11px] leading-5 text-amber-800">You can prepare sender accounts and templates now. Delivery starts only after public hosting and sender verification are enabled.</p></div></div>
      <Card><CardHeader title="1. Sender accounts" subtitle="Connect the mailbox that will send outreach. Presets fill the technical fields for you." action={<Link to="/email/senders" className="text-xs font-semibold text-indigo-600">Open sender workspace</Link>}/><CardBody><div className="grid gap-5 xl:grid-cols-[1fr_.9fr]"><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Email provider<select defaultValue="" onChange={(e) => applyPreset(e.target.value)} className={inputClass}><option value="">Choose a preset</option>{smtpProviderPresets.map((preset) => <option key={preset.id} value={preset.id}>{preset.label}</option>)}</select></label><Field label="Account label" value={smtpName} onChange={setSmtpName}/><Field label="SMTP host" value={smtpHost} onChange={setSmtpHost}/><Field label="Port" type="number" value={smtpPort} onChange={(v) => setSmtpPort(Number(v) || 587)}/><Field label="Username" value={smtpUsername} onChange={setSmtpUsername}/><Field label="Password / app password" type="password" value={smtpPassword} onChange={setSmtpPassword}/><Field label="From name" value={smtpFromName} onChange={setSmtpFromName} placeholder={profile.agencyName || "Agency name"}/><Field label="From email" type="email" value={smtpFromEmail} onChange={setSmtpFromEmail} placeholder="Optional override"/><label className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={smtpSecure} onChange={(e) => setSmtpSecure(e.target.checked)}/>Use direct SSL/TLS</label><div className="sm:text-right"><Button onClick={() => void saveSender()} loading={busy} icon={<IconMail size={14}/>}>Save sender</Button></div></div>
        <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-4"><p className="text-xs font-semibold text-slate-900">Connected senders</p><div className="mt-3 space-y-2">{smtpAccounts.length ? smtpAccounts.map((account) => <div key={account.id} className={`rounded-lg border bg-white p-3 ${selectedSmtpId === account.id ? "border-indigo-300 ring-2 ring-indigo-100" : "border-slate-200"}`}><button type="button" onClick={() => setSelectedSmtpId(account.id)} className="w-full text-left"><p className="text-xs font-semibold text-slate-900">{account.name}</p><p className="mt-1 truncate text-[10px] text-slate-500">{account.username} · {account.host}:{account.port}</p></button><button type="button" onClick={() => void removeSender(account.id)} className="mt-2 text-[10px] font-semibold text-rose-600">Remove</button></div>) : <p className="rounded-lg border border-dashed border-slate-200 bg-white p-5 text-center text-[11px] text-slate-500">No sender connected yet.</p>}</div>{smtpAccounts.length > 0 && <div className="mt-4 flex gap-2"><input type="email" value={smtpTestEmail} onChange={(e) => setSmtpTestEmail(e.target.value)} placeholder="Test recipient" className="h-8 min-w-0 flex-1 rounded-lg border border-slate-200 px-2 text-xs"/><Button variant="outline" size="sm" onClick={() => void testSender()} disabled={busy}>Send test</Button></div>}</div></div></CardBody></Card>

      <Card><CardHeader title="2. Default outreach message" subtitle="Create the starting email used for a lead source. Campaigns can still override it."/><CardBody className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><label className={labelClass}>Lead source<select value={templateSource} onChange={(e) => { setTemplateSource(e.target.value); void loadTemplate(e.target.value); }} className={inputClass}>{sources.map((source) => <option key={source.value} value={source.value}>{source.label}</option>)}</select></label><Field label="Template name" value={templateName} onChange={setTemplateName}/><Field label="Subject line" value={templateSubject} onChange={setTemplateSubject}/></div><EmailComposer label="Email body" description="Format the message visually and insert personalization fields without editing HTML." textValue={templateBody} htmlValue={templateBodyHtml} onTextChange={setTemplateBody} onHtmlChange={setTemplateBodyHtml} tokenHint="{{business_name}} {{city}} {{state}} {{website}} {{sender_name}}" previewTitle="Outreach email preview"/></CardBody></Card>

      <Card><CardHeader title="3. Delivery and follow-up" subtitle="Human-readable timing defaults for new campaigns."/><CardBody className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Field label="Delay between emails (seconds)" type="number" value={Math.max(.25, sendIntervalMs / 1000)} onChange={(v) => setSendIntervalMs(Math.max(250, Number(v) * 1000 || 1000))}/><Field label="Follow-up after (days)" type="number" value={Math.max(1, Math.round(followUpDelayHours / 24))} onChange={(v) => setFollowUpDelayHours(Math.max(1, Number(v) || 3) * 24)}/><Field label="Retry attempts" type="number" value={maxRetries} onChange={(v) => setMaxRetries(Math.max(0, Number(v) || 0))}/></div><label className="flex items-center gap-2 text-xs font-semibold text-slate-700"><input type="checkbox" checked={followUpEnabled} onChange={(e) => setFollowUpEnabled(e.target.checked)}/>Send one automatic follow-up when there is no reply</label>{followUpEnabled && <div className="space-y-4 border-t border-slate-100 pt-4"><Field label="Follow-up subject" value={followUpSubject} onChange={setFollowUpSubject}/><EmailComposer label="Follow-up body" description="This message is sent only when the lead has not replied or unsubscribed." textValue={followUpBody} htmlValue={followUpBodyHtml} onTextChange={setFollowUpBody} onHtmlChange={setFollowUpBodyHtml} tokenHint="{{business_name}} {{city}} {{state}} {{website}} {{sender_name}}" previewTitle="Follow-up preview"/></div>}<div className="flex justify-end"><Button onClick={() => void saveTemplate()} loading={busy} icon={<IconCheckCircle size={14}/>}>Save outreach defaults</Button></div></CardBody></Card>
    </div>}
  </section>;
}